### ISSUE TITLE
Outgoing calls

### ISSUE THREAD

**Issue by spointer** [davehorton/drachtio-astmrf#1]
Hi,
I can access medias flows from incoming calls using drachtio-astmrf, incoming RTP packet capturing and Asterisk ari playback.
Now i'd like to access and handle medias from outgoing calls but have no luck.

Can i make outgoing call using drachtio-srf's createUAC and drachtio-astmrf and use Asterisk as a media server?

Thank you.

**Comment by davehorton** [comment]
Hmm.  I have part of the answer, but being no asterisk expert hopefully you can help me work out the rest..

The first thing to do is just to create an endpoint (initially inactive) on the asterisk:

```
const ep = ms.createEndpoint();
console.log(`allocated sdp ${ep.local.sdp}` on asterisk);
```
The reason I log it out here is that may have "a=inactive", and if so we would need to change that to "a=sendrecv" before offering it in our outdial.  So if that is the case you would need to modify the sdp accordingly.

Then we can use `Srf#createUAC` and offer that sdp (or the modified version):
```
const dlg = srf.createUAC(uri, {
   localSdp: ep.local.sdp /* or the modified version */
});
```
Now, having connected the call, we need to go back and tell asterisk to stream that endpoint to `dlg.local.sdp` -- ie the sdp provided in the 200 answer.

OK, that is what I don't know how to do.....we have an ari channel in `ep.channel`, but is there a command to re-INVITE a channel / modify it to stream to a different SDP mid-call?

**Comment by spointer** [comment]
If i can create local sdp, i can know the remote sdp through createUAC() call first, so i think i can tell Asterisk the remote sdp through createEndpoint(). 
Do you think this is the right approach?

**Comment by davehorton** [comment]
I'm not sure I follow.  My proposed sequence was
1. create an inactive endpoint on Asterisk (createEndpoint, with no remoteSdp)
2. outdial with that endpoint (createUAC)
3. modify the endpoint on asterisk to stream to the remote endpoint.

Are you suggesting a different flow?

**Comment by spointer** [comment]
OK, I did what you suggested, and it works fine and i could handle media flows like a charm. Thank you.

**Comment by davehorton** [comment]
can you share the code on how you accoomplished step 3 above?  I'd be interested to know

**Comment by spointer** [comment]
Actually, i did not modified the endpoint, i just created my own active(sendrecv) and available sdp and set it to opts.remoteSdp in step 1. I think Asterisk try to learn the RTP port.
