### ISSUE TITLE
cdr event is not emitted properly

### ISSUE THREAD

**Issue by spointer** [davehorton/drachtio-astmrf#9]
Hi Dave,
When i use the drachtio-server v0.8.6, cdr events are not emitted properly. (Only the cdr event which contains application source is emitted on cdr:attempt and so on.)
I think this is related with your recent commit(e717558ce).

Please check this out. Thanks.

**Comment by davehorton** [comment]
I don;t see that commit in the repo, can you give me a link to it?

**Comment by spointer** [comment]
Sorry, i was mistaken. My drachtio-server version is v0.8.6-rc1-5-g45e27e14. 
Anyway, when i use v0.8.5.3, cdr event emitted properly ie, network and application source cdr attempt events were all emitted as expected but when use v0.8.6, UAC attempt event is not emitted. 
Any clues??

**Comment by davehorton** [comment]
right, thanks, I think I see the problem and just committed a fix on the develop branch.  When you have a chance could you test  it?

**Comment by spointer** [comment]
CDR events are emitted as expected after rebuilding(drachtio-server v0.8.6-rc1-6-g70308411)
Thank you so much and i close this issue right now.
